Add lifecycle experimental badge
RMI-PACTA/pacta.pkgdown.template pull request #17
Opened 2024-01-29 09:57 UTC by jdhoffa

`experimental` or `maturing` here? 

I expect we still may want to totally revamp our `pkgdown` sites.

2024-01-29 10:04 UTC, cjyetman commented
my not-so-important opinion here is that this repo is "mature" in that it does what it's supposed to do, we've been actively using it on public facing pages for many months, and there's no unsolved problems or bugs to fix (that I'm aware of). Sure, we may decide to change up the styling, but the basic functionality is pretty stable.

2024-01-29 17:13 UTC, AlexAxthelm commented
+1 for mature.

Rationale: This repo doesn't have many PRs against it, and even if it did, none of them would be introducing what we would consider "breaking changes" for the rendered HTML.

2024-01-29 17:17 UTC, cjyetman commented
I'd say it's "stable" then since how it's used is unlikely to change, though it's content/styling might change

2024-01-29 17:19 UTC, jdhoffa commented
Will change tomorrow when I'm back at the computer

2024-01-30 08:36 UTC, AlexAxthelm requested changes

2024-01-30 08:36 UTC, AlexAxthelm commented on README.md
> +[![Lifecycle: stable](https://img.shields.io/badge/lifecycle-stable-brightgreen.svg)](https://lifecycle.r-lib.org/articles/stages.html#stable)
```suggestion
[![Lifecycle: stable](https://img.shields.io/badge/lifecycle-stable-brightgreen.svg)](https://lifecycle.r-lib.org/articles/stages.html#stable)
```

Looks like you added `stable` without removing `experimental`

2024-01-30 08:36 UTC, AlexAxthelm commented on README.md
> +[![Lifecycle: stable](https://img.shields.io/badge/lifecycle-stable-brightgreen.svg)](https://lifecycle.r-lib.org/articles/stages.html#stable)
```suggestion
[![Lifecycle: stable](https://img.shields.io/badge/lifecycle-stable-brightgreen.svg)](https://lifecycle.r-lib.org/articles/stages.html#stable)
```

Looks like you added `stable` without removing `experimental`

2024-01-30 08:41 UTC, cjyetman approved these changes

2024-01-30 09:52 UTC, AlexAxthelm approved these changes

2024-01-30 09:55 UTC, merged